IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'IIS APPPOOL\ApiCuentas')
CREATE LOGIN [IIS APPPOOL\ApiCuentas] FROM WINDOWS
GO
CREATE USER [IIS APPPOOL\ApiCuentas] FOR LOGIN [IIS APPPOOL\ApiCuentas]
GO
