SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[SP_MTTO_MAE_ESTADO_CUENTA]
(
	@TIPO_ACTUALIZA INT,
	@IDMAEESTADOCUENTA INT OUTPUT,
	@IDCUENTA INT,
	@MES INT = NULL,
	@ANIO INT = NULL,
	@FECHA_CORTE DATE = NULL,
	@INTERES_BONIFICABLE DECIMAL(18,4) = NULL,
	@PAGO_CONTADO DECIMAL(18,4) = NULL,
	@SALDO_TOTAL DECIMAL(18,4) = NULL,
	@FILAS_AFECTADAS INT OUTPUT,
	@NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS 
BEGIN
	
	SET NOCOUNT ON

	SELECT @NUMERO_ERROR=0,@MENSAJE_ERROR='',@FILAS_AFECTADAS=0

	BEGIN TRY 
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			SELECT @IDMAEESTADOCUENTA =ISNULL(MAX(IdMaeEstadoCuenta),0)+1
			FROM MaeEstadoCuenta WITH(NOLOCK)

			SELECT @FECHA_CORTE = DATEFROMPARTS( ISNULL(@ANIO,YEAR(GETDATE())), ISNULL(@MES,MONTH(GETDATE())), DiaCorte)
			FROM Cuenta WITH(NOLOCK)
			WHERE IdCuenta = @IDCUENTA

			INSERT INTO MaeEstadoCuenta(IdMaeEstadoCuenta, IdCuenta, Mes, Anio, FechaCorte, InteresBonificable, PagoContado, SaldoTotal, Fecha_Crea, Fecha_Modifica)
			VALUES(@IDMAEESTADOCUENTA,@IDCUENTA,@MES,@ANIO,@FECHA_CORTE,@INTERES_BONIFICABLE,@PAGO_CONTADO,@SALDO_TOTAL, GETDATE(),GETDATE())

		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE dbo.MaeEstadoCuenta SET 
			Mes = @MES,
			Anio = @ANIO,
			FechaCorte = @FECHA_CORTE,
			InteresBonificable = @INTERES_BONIFICABLE,
			PagoContado = @PAGO_CONTADO,
			SaldoTotal = @SALDO_TOTAL,
			Fecha_Modifica = GETDATE()
			WHERE IdMaeEstadoCuenta = @IDMAEESTADOCUENTA
			AND IdCuenta = @IDCUENTA

		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN

			DELETE FROM MaeEstadoCuenta
			WHERE  IdMaeEstadoCuenta = @IDMAEESTADOCUENTA
			AND IdCuenta = @IDCUENTA

		END
		
		SELECT @FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH

		SELECT @NUMERO_ERROR=ERROR_NUMBER(), @MENSAJE_ERROR=ERROR_MESSAGE()
	END CATCH;
FINA:
END
GO
