SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[SP_MTTO_CUENTA]
(
	@TIPO_ACTUALIZA INT,
	@IDCUENTA INT OUTPUT,
	@IDUSUARIO INT,
	@NUMERO_CUENTA VARCHAR(50) = NULL,
	@PORCENTAJE_INTERES DECIMAL(10,4) = NULL,
	@PORCENTAJE_PAGO_MIN DECIMAL(10,4) = NULL,
	@LIMITE_CREDITO DECIMAL(18,4) = NULL,
	@DIA_CORTE DECIMAL(18,4) = NULL,
	@PAGO_CONTADO DECIMAL(18,4) = NULL,
	@SALDO_TOTAL DECIMAL(18,4) = NULL,
	@FILAS_AFECTADAS INT OUTPUT ,
	@NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS 
BEGIN
	
	SET NOCOUNT ON

	SELECT @NUMERO_ERROR=0,@MENSAJE_ERROR='',@FILAS_AFECTADAS=0

	BEGIN TRY 
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			SELECT @IDCUENTA=ISNULL(MAX(IdCuenta),0)+1
			FROM Cuenta

			INSERT INTO dbo.Cuenta(IdCuenta, IdUsuario, NumeroTarjeta, PorcentajeInteres, PorcentajePagoMin, LimiteCredito, DiaCorte,PagoContado,Saldo, Fecha_Crea, Fecha_Modifica)
			VALUES(@IDCUENTA, @IDUSUARIO,@NUMERO_CUENTA,@PORCENTAJE_INTERES,@PORCENTAJE_PAGO_MIN,@LIMITE_CREDITO,@DIA_CORTE,@PAGO_CONTADO,@SALDO_TOTAL, GETDATE(), GETDATE())

		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE Cuenta SET 
			NumeroTarjeta = @NUMERO_CUENTA,
			PorcentajeInteres = @PORCENTAJE_INTERES,
			PorcentajePagoMin = @PORCENTAJE_PAGO_MIN,
			LimiteCredito = @LIMITE_CREDITO,
			DiaCorte = @DIA_CORTE,
			PagoContado = @PAGO_CONTADO,
			Saldo = @SALDO_TOTAL,
			Fecha_Modifica = GETDATE()
			WHERE IdUsuario = @IDUSUARIO
			AND IdCuenta = @IDCUENTA

		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN

			DELETE FROM Cuenta
			WHERE IdUsuario = @IDUSUARIO
			AND IdCuenta = @IDCUENTA

		END
		
		SELECT @FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		SELECT @NUMERO_ERROR=ERROR_NUMBER(), @MENSAJE_ERROR=ERROR_MESSAGE(), @FILAS_AFECTADAS = 0
	END CATCH;
FINA:
END
GO
