SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[SP_MTTO_USUARIO]
(
	@TIPO_ACTUALIZA INT,
	@IDUSUARIO INT OUTPUT,
	@NOMBRE VARCHAR(50) = NULL,
	@APELLIDO VARCHAR(50) = NULL,
	@EDAD INT = NULL,
	@CORREO VARCHAR(50) = NULL,
	@USUARIO VARCHAR(20) = NULL,
	@CONTRASENA VARCHAR(100) NULL,
	@FILAS_AFECTADAS INT OUTPUT,
	@NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS 
BEGIN
	
	SET NOCOUNT ON

	SELECT @NUMERO_ERROR=0,@MENSAJE_ERROR='',@FILAS_AFECTADAS=0

	BEGIN TRY 
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			SELECT @IDUSUARIO=ISNULL(MAX(IdUsuario),0)+1
			FROM Usuario

			INSERT INTO Usuario([IdUsuario], [Nombre], [Apellido], [Edad], [Correo], [Usuario], [Contrasena], [Fecha_Crea],[Fecha_Actualiza])
			 VALUES( @IDUSUARIO, @NOMBRE, @APELLIDO, @EDAD, @CORREO, @USUARIO, @CONTRASENA , GETDATE(),GETDATE())

		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
		UPDATE Usuario SET
		Nombre = @NOMBRE, 
		Apellido = @APELLIDO,
		Edad = @EDAD,
		Correo = @CORREO,
		Usuario = @USUARIO,
		Contrasena = @CONTRASENA,
		Fecha_Actualiza = GETDATE()
		WHERE IdUsuario = @IDUSUARIO

		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM Usuario
			WHERE IdUsuario = @IDUSUARIO
		END
		
		SELECT @FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH

		SELECT @NUMERO_ERROR=ERROR_NUMBER(), @MENSAJE_ERROR=ERROR_MESSAGE(), @FILAS_AFECTADAS = 0
	END CATCH;
FINA:
END
GO
